services:
  springapp:
    image: fbravo03/clustertest-back:estesi
    container_name: springapp
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:lts
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pruebadb
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
